module.exports = [
    { altura: 1.80, sexo: 'M' },
    { altura: 1.67, sexo: 'F' },
    { altura: 1.71, sexo: 'M' },
    { altura: 1.46, sexo: 'F' },
    { altura: 1.95, sexo: 'M' },
    { altura: 2.01, sexo: 'M' },
    { altura: 1.72, sexo: 'F' },
    { altura: 1.79, sexo: 'M' },
    { altura: 1.88, sexo: 'M' },
    { altura: 1.65, sexo: 'F' },
    { altura: 1.83, sexo: 'M' },
    { altura: 1.89, sexo: 'M' },
    { altura: 1.65, sexo: 'F' },
    { altura: 1.55, sexo: 'F' },
    { altura: 1.72, sexo: 'F' },
];